# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e49b716376c69511811522597321251d1804867b8858c778839735186e56d5ba16ff23fa58663a2272a1f376857e315ace121d85385716303ebddc461ec8da4

test:
  secret_key_base: 9c29144b572920ca6e185f1f637f9c4f7f94c51db30409466317b225ad6448518a17ba8716456d14a1eab8841a8bbba6ea5c19674f8cfed786118689dab4f221

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
